# Generated by Django 3.2.4 on 2021-06-12 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spheres', '0001_initial'),
        ('districts', '0001_initial'),
        ('themes', '0001_initial'),
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='event_images')),
                ('is_free', models.BooleanField()),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('restriction', models.PositiveIntegerField(default=0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='districts.district')),
                ('spheres', models.ManyToManyField(to='spheres.Sphere')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spots.spot')),
                ('themes', models.ManyToManyField(to='themes.Theme')),
            ],
        ),
    ]
