# Generated by Django 3.2.4 on 2021-06-13 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0002_auto_20210613_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='place_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spots.placetype'),
        ),
    ]
