# Generated by Django 3.2.4 on 2021-06-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0003_alter_spot_place_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='address',
            field=models.CharField(default='', max_length=300, null=True),
        ),
    ]
